# this file is a helper to run and test locally
# starts a postgres instance on port 5450 to use as a local db
version: '3.6'
services:
  db:
    image: postgres:15
    ports:
      - '5450:5432' # expose pg on port 5450 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yu-template
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  db_is_ready:
    image: db
    depends_on:
      db:
        condition: service_healthy

  db_test:
    image: postgres:15
    restart: always
    ports:
      - '5451:5432' # expose pg on port 5451 to not collide with pg from elswhere
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  db_test_is_ready:
    image: db_test
    depends_on:
      db_test:
        condition: service_healthy

volumes:
  db_data:
